#!/usr/bin/env python
import sys
import getopt
import subprocess


def main(argv):
    inputfile = []
    outputfile = ''
    correctsyntax = 'mergeva -i <inputfile1> -i <inputfilen...> -o <outputfile>'
    try:
        opts, args = getopt.getopt(argv, "hi:o:", ["ifile=", "ofile="])
    except getopt.GetoptError:
        print correctsyntax
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print correctsyntax
            sys.exit()
        elif opt in ("-i", "--ifile"):
            inputfile.append('-i')
            inputfile.append(arg)
        elif opt in ("-o", "--ofile"):
            outputfile = arg
    if inputfile != [] and outputfile != '':
        commands = ['ffmpeg']
        commands.extend(inputfile)
        commands.extend(['-strict', '-2'])
        commands.append(outputfile)
        p = subprocess.Popen(commands, stdout=subprocess.PIPE)
        output, err = p.communicate()
        print "*** running fmpeg merge ***\n", output
    else:
        print correctsyntax
        sys.exit(2)

if __name__ == "__main__":
    main(sys.argv[1:])
